controllers/ActorsController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\data\ActiveDataProvider;
use app\models\Casting;

class ActorsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Casting::find(),
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);
        $this->view->params['dataProvider'] = $dataProvider;
        return $this->render('index');
    }

    public function actionView($id = '')
    {
        $casting = Casting::find()->where(['id' => (int)$id])->one();
        return $this->render('show', [
            'casting' => $casting
        ]);
    }
}

controllers/GenresController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\data\ActiveDataProvider;
use app\models\Genres;

class GenresController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Genres::find(),
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);
        $this->view->params['dataProvider'] = $dataProvider;
        return $this->render('index');
    }

    public function actionView($id = '')
    {
        $genre = Genres::find()->where(['id' => (int)$id])->one();
        return $this->render('show', [
            'genre' => $genre
        ]);
    }
}

controllers/MoviesController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\data\ActiveDataProvider;
use app\models\Movies;

class MoviesController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Movies::find(),
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);
        $this->view->params['dataProvider'] = $dataProvider;
        return $this->render('movies');
    }

    public function actionView($id = '')
    {
        $trailerFileName = '';
        $movie = Movies::find()->where(['id' => (int)$id])->one();
        $trailerPath = Yii::getAlias('@app/web/movie_assets').DIRECTORY_SEPARATOR.$movie->external_id.DIRECTORY_SEPARATOR.'videos';
        $files = scandir($trailerPath);
        // first two elements will always be . and ..
        if (isset($files[2])) {
            $trailerFileName = $files[2];
        }
        $trailerMoviePath = '/movie_assets/'.$movie->external_id.'/videos/'.$trailerFileName;
        return $this->render('show', [
            'movie' => $movie,
            'trailer' => $trailerMoviePath
        ]);
    }
}

controllers/SourcesController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\Sources;
use app\models\Movies;
use app\components\Helper;
use yii\data\ActiveDataProvider;
use yii\helpers\Json;

class SourcesController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Sources::find(),
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);
        $this->view->params['dataProvider'] = $dataProvider;
        return $this->render('sources');
    }

    public function actionAdd()
    {
        $model =  new Sources();
        if ($model->load(Yii::$app->request->post())) {
            $model->user_id = 1;
            $model->processed = 0;
            $model->date_added = date('Y-m-d H:i:s');
            if($model->save()) {
                Yii::$app->session->setFlash('source added');
                return $this->redirect(['sources/index']);   
            } else {
                Yii::$app->session->setFlash($model->getErrors());
                return $this->render('add', [
                   'model' => $model,
                ]);                
            }

 
        } else {
           return $this->render('add', [
               'model' => $model,
           ]);
        }
    }

    public function actionRun()
    {
        /**
         * different approaches
         * normally we should change this in php.ini but giving the fact that this
         * code will be executed on another machine we will set the time limit here
         * 
         * if time++ we can run separate php threads for every item. This should increase the performance
         * */
        set_time_limit(120);
        $movie = new Movies();
        $source = Sources::find()->where(['processed' => 0])->one();
        if($source instanceof Sources && $source->source_url) {
            $url = $source->source_url;
            $result = file_get_contents($url);
            $resultSanitized = Helper::utf8ize($result);
            $convertedResult = Json::decode($resultSanitized);
            if (count($convertedResult)) {
                foreach($convertedResult as $item) {
                    //save assets for every movie
                    $assetSaved = $source->saveItemAssets($item);
                    if ($assetSaved) {
                        $movie->setParamsAndSave($item);

                    }
                }
                $source->processed = 1;
                $source->save();
                Yii::$app->session->setFlash('success', "assets saved");
            }
        } else {
            Yii::$app->session->setFlash('warning', "No unprocessed sources found");
        }
        return $this->redirect(['sources/index']);  
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'Sources', 'url' => ['/sources/index']],
            ['label' => 'Run sources', 'url' => ['/sources/run']],
            ['label' => 'Movies', 'items' => [
                 ['label' => 'Movies', 'url' => '/movies/index'],
                 '<li class="divider"></li>',
                 ['label' => 'Actors', 'url' => '/actors/index'],
                 '<li class="divider"></li>',
                 ['label' => 'Genres', 'url' => '/genres/index'],
                 '<li class="divider"></li>',
                 ['label' => 'Directors', 'url' => '/directors/index'],

            ]],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Tudorel Maciuca <?= date('Y') ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>