controllers/ActorsController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\data\ActiveDataProvider;
use app\models\Casting;

class ActorsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Casting::find(),
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);
        $this->view->params['dataProvider'] = $dataProvider;
        return $this->render('index');
    }

    public function actionView($id = '')
    {
        $casting = Casting::find()->where(['id' => (int)$id])->one();
        return $this->render('show', [
            'casting' => $casting
        ]);
    }
}

controllers/DirectorsController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\data\ActiveDataProvider;
use app\models\Directors;

class DirectorsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Directors::find(),
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);
        $this->view->params['dataProvider'] = $dataProvider;
        return $this->render('index');
    }

    public function actionView($id = '')
    {
        $director = Directors::find()->where(['id' => (int)$id])->one();
        return $this->render('show', [
            'director' => $director
        ]);
    }
}

controllers/GenresController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\data\ActiveDataProvider;
use app\models\Genres;

class GenresController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Genres::find(),
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);
        $this->view->params['dataProvider'] = $dataProvider;
        return $this->render('index');
    }

    public function actionView($id = '')
    {
        $genre = Genres::find()->where(['id' => (int)$id])->one();
        return $this->render('show', [
            'genre' => $genre
        ]);
    }
}

controllers/MoviesController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\data\ActiveDataProvider;
use app\models\Movies;

class MoviesController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Movies::find(),
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);
        $this->view->params['dataProvider'] = $dataProvider;
        return $this->render('movies');
    }

    public function actionView($id = '')
    {
        $trailerFileName = '';
        $movie = Movies::find()->where(['id' => (int)$id])->one();
        $trailerPath = Yii::getAlias('@app/web/movie_assets').DIRECTORY_SEPARATOR.$movie->external_id.DIRECTORY_SEPARATOR.'videos';
        $files = scandir($trailerPath);
        // first two elements will always be . and ..
        if (isset($files[2])) {
            $trailerFileName = $files[2];
        }
        $trailerMoviePath = '/movie_assets/'.$movie->external_id.'/videos/'.$trailerFileName;
        return $this->render('show', [
            'movie' => $movie,
            'trailer' => $trailerMoviePath
        ]);
    }
}

views/movies/movies.php
<?php
use yii\grid\GridView;
use yii\helpers\Html;
/* @var $this yii\web\View */

$this->title = 'Movies';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-index">
	<h1>Movies</h1>
	<div class="site-about">
		<?php
			echo GridView::widget([
			    'dataProvider' => $this->params['dataProvider'],
			    'columns' => [
			        [
			            'label' => 'ID',
			            'format' => 'raw',
			            'attribute' => 'id',
			            'value' => function ($data) {
			                return Html::a($data['id'], array('movies/view', 'id'=>$data['id']));
			            },
			        ],			    	
			        'external_id',
			    	'headline'
			    ]
			]);
		?>
	</div>
</div>

views/movies/show.php
<?php
use yii\helpers\Html;
/* @var $this yii\web\View */
/* @var $movie app\models\Movies */
/* @var $trailer string */
$this->title = $movie->headline;
$this->params['breadcrumbs'][] = ['label' => 'Movies', 'url' => ['index']];
$this->params['breadcrumbs'][] = $movie->headline;

?>



<div class="site-index">

    <div class="jumbotron">
        <h1><?php echo $movie->headline;?></h1>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <video width="320" height="240" controls>
                    <source src="<?php echo $trailer;?>" type="video/mp4">
                    Your browser does not support the video tag.
                </video>
            </div>
            <div class="col-lg-4">
                <?php echo $movie->body;?>
            </div>
            <div class="col-lg-4">
                <div class="cast">
                    <h2>Cast</h2>
                    <?php
                        foreach ($movie->castingMovies as $cast)
                        {
                            echo '<p>';
                            echo Html::a($cast->casting->name, array('actors/view', 'id'=>$cast->casting->id));
                            echo '</p>';
                        }
                    ?>
                </div>
                <div class="genre">
                    <h2>Genre</h2>
                    <?php
                        foreach ($movie->genresMovies as $genre)
                        {
                            echo '<p>';
                            echo Html::a($genre->genre->type, array('genres/view', 'id'=>$genre->genre->id));
                            echo '</p>';
                        }
                    ?>
                </div>
                <div class="directors">
                    <h2>Directors</h2>
                    <?php
                        foreach ($movie->directorMovies as $director)
                        {
                            echo '<p>';
                            echo Html::a($director->director->name, array('directors/view', 'id'=>$director->director->id));
                            echo '</p>';
                        }
                    ?>
                </div>
            </div>
        </div>

    </div>
</div>